### PR TITLE
Fix EZP-25064: Content Items instead of Contents

### PR DESCRIPTION
**Pull request by peterkeung**
As per https://jira.ez.no/browse/EZP-25064 to stop using "contents"

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by peterkeung** [comment]
Would be nice to use {% trans %} and {% plural %} but we'll save that for next time :)

**Comment by andrerom** [comment]
ping @dpobel

**Comment by dpobel** [comment]
@peterkeung it seems like you are highly motivated by this topic, so I'm gonna merge this PR ;-)

That said, this bundle is not meant to serve as a model for the server side development and it's intentionally over simplified in many aspects to keep it small so that the whole concept is easier to get.

**Comment by peterkeung** [comment]
Understood!  And yes, I'm trying to get some momentum to clean up this "content items" issue :smile:

**Pull request merged**
